version: "3"
# Link: https://gist.github.com/Warchant/0d0f0104fe7adf3b310937d2db67b512
services:
  sonarqube:
    depends_on:
        - sonarqube-db
    image: sonarqube:8.8-community
    expose:
      - 9999
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
      - 9999:9000
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - .:/healthcheck
    healthcheck:
      test: /healthcheck/docker-healthcheck
      interval: 10s
      timeout: 5s
      retries: 5      

  sonarqube-db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    
  scanner:
    user: ${UID}:${GID}
    depends_on:
      - sonarqube
      - sonarqube-db      
    image: sonarsource/sonar-scanner-cli
    networks:
      - sonarnet
    volumes: 
      - ${PROJECT_SOURCE}:/usr/src
      - ${PROJECT_SOURCE}:/opt/sonar-scanner/conf
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000

networks:
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data: